# Generated by Django 4.2 on 2023-07-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_blog_author_blog_image_alter_blog_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Restoran İsmi')),
                ('image', models.ImageField(default='', upload_to='pages', verbose_name='Restoran Resimleri')),
                ('body', models.TextField()),
            ],
        ),
    ]
