# Generated by Django 4.2 on 2023-07-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='', upload_to='pages/', verbose_name='Restoran Resimleri'),
        ),
    ]
